import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row h-screen w-full">
          
          <Sidebar />
          
          {/* 
            flex-1 : 나머지 부분 모두 차지
            bg-gray-800 : 회색 800만큼 찐하게 (50~950)
            ps-8 : 왼쪽 패딩 8 (2rem, 32px)
            h-screen : height 100vh
            overflow-auto : 스크롤 대비
            text-white : 배경이 검정계열이니까 글자는 하얀색으로
          */}
          <div className="flex-1 bg-gray-800 ps-8 h-screen overflow-auto text-white">
            {children}
          </div>
        </div>


      </body>
    </html>
  );
}

// main.jsx -> App컴포넌트
// layout.tsx -> page.tsx